name: NodeJS with Webpack

on:
  # manually trigger the workflow
  dispatch_event:
    name: webpack
    payload:
      branch: master

  # 'push' is the default event
  push:
    paths:
      - src/*
    branches:
      - master
  pull_request:
    paths:
      - src/*
    branches:
      - master

jobs:
  # Build
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      # publish on GitHub
      - name: Publish
        run: |
          yarn build:prod
          yarn build:dev
          git add .
          git commit -m "Build Dist Folders"
          git push origin master
