name: NodeJS with Webpack

on:
  # manually run w/o using the webpack command
  workflow_dispatch:

  # 'push' is the default event
  push:
    paths:
      - src/*
    branches:
      - master
  pull_request:
    paths:
      - src/*
    branches:
      - master
  release:
    types: [published]

jobs:
  # Build
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    vars:
      - AUTHOR_NAME: ${{ github.event.head_commit.author.name }}
      - AUTHOR_EMAIL: ${{ github.event.head_commit.author.email }

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn

      # publish on GitHub
      - name: Publish
        run: |
          yarn build:prod
          yarn build:dev

          echo "${{ GITHUB_ACTOR }} - ${{ AUTHOR_NAME }} : ${{ AUTHOR_EMAIL }}"

          git config --global user.email "tamsmoha@gmail.com"
          git config --global user.name "tamsamani"
          git config --global github.token "${{ secrets.GITHUB_TOKEN }}"

          git add ./dist/*
          git commit -m "Build Dist Files"
          git push origin master
